// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3LMK_GPrdTYoNijlPSablfSFfg3KRFtM',
    appId: '1:20279351641:android:8f178bb4290204647bd448',
    messagingSenderId: '20279351641',
    projectId: 'fluccino',
    storageBucket: 'fluccino.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbDfHe6qBw_NstVo76be7f3hCLjLv21SY',
    appId: '1:20279351641:ios:75dbfc9e8d8e882c7bd448',
    messagingSenderId: '20279351641',
    projectId: 'fluccino',
    storageBucket: 'fluccino.appspot.com',
    iosClientId:
        '20279351641-2jdrdl90u4a5vjmr5p7l67lommds6pt5.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffe',
  );
}
